name: Running pytest suite
on: [pull_request]
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Fetch main repository
        uses: actions/checkout@v3
        with:
          path: ./
      - name: Run pytest suite
        run: >
          docker compose build --build-arg PYTHON_VERSION=${{ matrix.python-version }} &&
          docker compose run --name tests tests
      - name: Run coverage
        run: >
          docker start tests &&
          docker exec tests coverage xml &&
          docker cp tests:/tmp/coverage.xml . &&
          docker exec tests coverage report
      - name: Publish coverage report to PR
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}


