name: Running pytest suite
on: [pull_request]
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        pydantic-version: ["1.*"]

    steps:
      - name: Fetch main repository
        uses: actions/checkout@v3
        with:
          path: ./
      # - name: Build test container
      #   run: >
      #     docker compose build
      #     --build-arg PYTHON_VERSION=${{ matrix.python-version }}
      #     --build-arg PYDANTIC_VERSION=${{ matrix.pydantic-version }} 
      #     tests
      # - name: Run test suite
      #   run: >
      #     docker compose run --name tests tests
      # - name: Run coverage report
      #   run: >
      #     docker start tests &&
      #     docker exec tests coverage xml &&
      #     docker cp tests:/tmp/coverage.xml . &&
      #     docker exec tests coverage report
      - name: Install Python dependencies
        run: >
          python -m pip install --upgrade pip 
          -r ./requirements.txt
          -r ./tests/requirements.txt
      - name: Run test suite
        run: >
          coverage run -m pytest ./tests
          -v
          -m "not performance"
          --durations=10
      - name: Run coverage report
        run: >
          coverage xml
      - name: Publish coverage report to PR
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}


