name: Running pytest suite
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run pytest suite
        run: docker-compose run --name tests tests
      - name: Run coverage
        run: >
          docker start tests &&
          docker exec tests coverage xml &&
          docker cp tests:/tmp/coverage.xml . &&
          docker exec tests coverage report
      - name: Publish coverage report to PR
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}


